# Generated by Django 4.1.3 on 2022-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_rename_captions_tag_caption")]

    operations = [
        migrations.RemoveField(model_name="post", name="image_name"),
        migrations.AddField(model_name="post", name="image", field=models.ImageField(null=True, upload_to="posts")),
    ]
